/**
 * Shared vision-analysis types and a non-static heuristic fallback.
 * The fallback is used only when Gemini/OpenAI are unavailable so
 * submission never fails. Scores still vary with image signals + text.
 */

export type VisionPriority = "Low" | "Medium" | "High" | "Critical";
export type FraudRisk = "LOW" | "MEDIUM" | "HIGH";

export interface VisionResult {
  authenticityScore: number;
  priorityLevel: VisionPriority;
  isLikelyFake: boolean;
  fraudRisk: FraudRisk;

  /** Clean AI reasoning (no internal debug text) — displayed to citizens in Step 5. */
  aiReasoning: string;

  /**
   * Officer-only structured insights (never shown to the citizen in Step 5).
   * Generated by the API; present only on server/AI-analysed complaints.
   */
  officerNote?: string;         // exact verification reason for the officer
  recommendedAction?: string;   // suggested next step (e.g. "Urgent sample collection")

  detectedObjects?: string;
  source: "openrouter" | "gemini" | "openai" | "heuristic";
}

export interface ImageSignals {
  width: number;
  height: number;
  aspect: number;
  entropy: number;
  edgeScore: number;
  fileBytes: number;
  filename: string;
}

export function clampScore(n: number): number {
  if (!Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(100, Math.round(n)));
}

export function severityFromVision(v: VisionResult): number {
  if (v.isLikelyFake || v.fraudRisk === "HIGH") {
    return clampScore(Math.min(v.authenticityScore, 32));
  }
  if (v.priorityLevel === "Critical") return clampScore(Math.max(88, v.authenticityScore));
  if (v.priorityLevel === "High") return clampScore(Math.max(72, v.authenticityScore));
  if (v.priorityLevel === "Medium") return clampScore(Math.min(69, Math.max(42, v.authenticityScore)));
  return clampScore(Math.min(39, v.authenticityScore));
}

function filenameLooksSpam(name: string): boolean {
  return /(wallpaper|screenshot|meme|stock|unsplash|pexels|download|selfie|avatar|cartoon|sticker)/i.test(
    name,
  );
}

/**
 * Variable heuristic used when no vision API key is configured.
 * Does NOT return a fixed score — scores vary with image signals + text.
 */
export function heuristicVisionAnalysis(
  complaintType: string,
  description: string,
  signals: ImageSignals | null,
  hasImage: boolean,
): VisionResult {
  if (!hasImage || !signals) {
    return {
      authenticityScore: 38,
      priorityLevel: "Medium",
      isLikelyFake: false,
      fraudRisk: "MEDIUM",
      aiReasoning:
        "No evidence photo was attached. This complaint could not be verified visually.",
      officerNote:
        "No photo submitted. Priority is based only on the written description. Treat as incomplete evidence and request documentation from the complainant during field visit.",
      recommendedAction:
        "🟡 Routine: Schedule field inspection and request original product packaging or bill as supporting evidence.",
      detectedObjects: "none",
      source: "heuristic",
    };
  }

  const { aspect, entropy, edgeScore, fileBytes, filename } = signals;
  const pixels = signals.width * signals.height;
  const text = `${complaintType} ${description}`.toLowerCase();

  let authenticity = 50;
  const notes: string[] = [];

  if (filenameLooksSpam(filename)) {
    authenticity -= 28;
    notes.push(`filename "${filename}" resembles stock/wallpaper/meme media`);
  }

  if (entropy < 2.2) {
    authenticity -= 35;
    notes.push("very low colour entropy — typical of wallpapers or generated graphics");
  } else if (entropy < 3.2) {
    authenticity -= 18;
    notes.push("limited colour variation; may be a graphic or heavily processed");
  } else if (entropy > 6.5 && edgeScore < 8) {
    authenticity -= 12;
    notes.push("noisy pixel pattern without clear object edges");
  } else if (entropy >= 4.2 && edgeScore >= 12) {
    authenticity += 16;
    notes.push("natural photo-like colour mix and edge detail consistent with a real capture");
  }

  if (aspect >= 2.05 || aspect <= 0.48) {
    authenticity -= 22;
    notes.push("extreme aspect ratio — common for wallpapers, not product close-ups");
  } else if (aspect >= 0.55 && aspect <= 0.85) {
    authenticity += 8;
    notes.push("portrait phone-photo aspect consistent with a field capture");
  }

  if (pixels < 40_000) {
    authenticity -= 20;
    notes.push("image too small; labels/expiry dates would not be readable");
  } else if (pixels > 350_000 && edgeScore >= 10) {
    authenticity += 6;
  }

  if (fileBytes < 8_000) {
    authenticity -= 15;
    notes.push("tiny file size; unlikely to contain readable packaging evidence");
  }

  const evidenceWords =
    /\b(expired|expiry|mould|mold|fungus|maggot|label|batch|packet|capsule|tablet|bottle|seal)\b/i.test(
      text,
    );
  if (evidenceWords && authenticity >= 50) {
    authenticity += 8;
    notes.push("complaint text describes inspectable physical evidence");
  }

  authenticity = clampScore(authenticity);

  const isLikelyFake = authenticity < 30;
  const fraudRisk: FraudRisk =
    authenticity < 30 ? "HIGH" : authenticity < 70 ? "MEDIUM" : "LOW";
  const priorityLevel: VisionPriority =
    authenticity < 30
      ? "Low"
      : /\b(child|hospital|spurious|poison|death|expired)\b/i.test(text)
        ? "High"
        : "Medium";

  // Citizen-facing message: clean, friendly, no internal debug text.
  const aiReasoning =
    authenticity < 30
      ? "The uploaded image does not appear to show the reported violation. It may be a generic photo, wallpaper, or unrelated image."
      : authenticity < 70
        ? "The uploaded image is partially related to the complaint. Evidence quality could be improved."
        : "The photo appears to show evidence relevant to the reported violation.";

  // Officer-only note: technical detail helpful for investigation.
  const officerNote =
    notes.length
      ? `Visual analysis (heuristic): ${notes.slice(0, 3).join("; ")}.`
      : "Image passed basic quality checks.";

  const isHighPriority = (["High", "Critical"] as VisionPriority[]).includes(priorityLevel);
  const recommendedAction =
    authenticity < 30
      ? "🔴 High Fraud Risk: Do not schedule field visit until complainant provides a clearer, product-specific photo. Request re-upload."
      : authenticity < 70
        ? "🟡 Routine: Inspect the establishment within 72 hours and collect a product sample for lab testing."
        : isHighPriority
          ? "🔴 Urgent: Schedule physical sample collection within 24 hours. Notify district health officer."
          : "🟡 Routine: Inspect retail licence and premises within 72 hours.";

  return {
    authenticityScore: authenticity,
    priorityLevel,
    isLikelyFake,
    fraudRisk,
    aiReasoning,
    officerNote,
    recommendedAction,
    detectedObjects: notes.slice(0, 2).join("; ") || "unspecified",
    source: "heuristic",
  };
}

export function parseVisionJson(raw: string): VisionResult | null {
  const cleaned = raw
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start < 0 || end <= start) return null;
  try {
    const obj = JSON.parse(cleaned.slice(start, end + 1)) as Record<string, unknown>;
    const authenticityScore = clampScore(Number(obj.authenticityScore));
    const priorityRaw = String(obj.priorityLevel ?? "Medium");
    const priorityLevel: VisionPriority =
      priorityRaw === "Critical" || priorityRaw === "High" || priorityRaw === "Low" || priorityRaw === "Medium"
        ? priorityRaw
        : "Medium";
    const isLikelyFake = Boolean(obj.isLikelyFake);
    const fraudRisk: FraudRisk =
      obj.fraudRisk === "HIGH" || obj.fraudRisk === "LOW" || obj.fraudRisk === "MEDIUM"
        ? obj.fraudRisk
        : isLikelyFake || authenticityScore < 30
          ? "HIGH"
          : authenticityScore < 70
            ? "MEDIUM"
            : "LOW";
    const aiReasoning = String(obj.aiReasoning ?? obj.reason ?? "").trim();
    const officerNote = obj.officerNote ? String(obj.officerNote).trim() : undefined;
    const recommendedAction = obj.recommendedAction
      ? String(obj.recommendedAction).trim()
      : undefined;
    if (!aiReasoning) return null;
    return {
      authenticityScore,
      priorityLevel,
      isLikelyFake,
      fraudRisk,
      aiReasoning,
      officerNote,
      recommendedAction,
      detectedObjects: obj.detectedObjects ? String(obj.detectedObjects) : undefined,
      source: "openrouter",
    };
  } catch {
    return null;
  }
}
